In [1]:
import numpy as np

In [2]:
#data types
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int64


In [3]:
#if we covert one value of array in float then 
#then entire will convert into float 
arr = np.array([1,2,3,4.25,5])
print(arr,arr.dtype)

[1.   2.   3.   4.25 5.  ] float64


In [9]:
arr2 =np.array([3+5j])
arr3 = np.array([4+5j])
print(arr2,arr2.dtype)
print(arr2+arr3)
print(arr2-arr3)

[3.+5.j] complex128
[7.+10.j]
[-1.+0.j]


In [12]:
arr4  = np.array(["prime",{1,2,3},3.24])
print(arr4,type(arr4))
print(arr4.dtype)

['prime' {1, 2, 3} 3.24] <class 'numpy.ndarray'>
object


In [19]:
arr2D= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_col = np.sum(arr2D,axis = 0)
print(sum_of_col)
sum_of_col = np.sum(arr2D,axis = 1)
print(sum_of_col)
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [30]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2*3*2 2 2d array or hrr 2d array ka size 2*3 hoga

print(arr3D,arr3D.shape)
#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])
#slicing
print(arr3D[:,0,: ])# first row from both layer
print(arr3D[:,:,0])# first column from both layer
arr3D[:, 0, :] = 99
print(arr3D)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [35]:
##vectorization
arr = np.array([1,2,3,4,5])
brr = np.array([4,5,6,7,8])
print(arr ** 2)
print(arr + 10)
print(arr+brr)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 5  7  9 11 13]


In [39]:
#boradcasting
print(arr+5) 
crr = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr+crr)
print(arr.shape)#(5,=>1*5)
print(crr.shape)

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 3  5  7  9 11]]
(5,)
(2, 5)


In [46]:
#normalize
arr = np.array([[1,2],[3,4]])
print(np.mean(arr))
print(np.std(arr))

mean = np.mean(arr)
std = np.std(arr)

norm = (arr - mean)/std

print(norm) 

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [54]:
#mathematics fucntions
arr3 = np.array([1,2,3,4,5])
print(np.sum(arr3))
print(np.max(arr3))
print(np.min(arr3))
print(np.prod(arr3))
print(np.argmin(arr3))
print(np.argmax(arr3))
print(np.mean(arr3))
print(np.std(arr3))
print(np.median(arr3))
print(np.var(arr3))


15
5
1
120
0
4
3.0
1.4142135623730951
3.0
2.0


In [55]:
arr = np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log2(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]


In [60]:
#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.24))

3.0
4.0
3.0
3.0
