In [1]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))
print(arr.dtype)
print(arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
int64
(5,)


In [11]:
#yai heterogenous hain toh isme isme 1 2 3 4 sari string ho jayge 
arr2 = np.array([1,2,3,4,5,"hello"])
print(arr2,type(arr2))
print(arr2.dtype)
print(arr2.shape)

['1' '2' '3' '4' '5' 'hello'] <class 'numpy.ndarray'>
<U21
(6,)


In [14]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(f"dimensiono is {arr2D.shape}")#dimension

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimensiono is (3, 3)


In [21]:
arr1= np.zeros((2,3),dtype = "int64")
print(arr1,arr1.shape)

arr3= np.ones((2,3))
print(arr3,arr3.shape)

arr3= np.ones((2,3), dtype= "int64")
print(arr3,arr3.shape)

arr4= np.full((3,4),100)
print(arr4,arr4.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [23]:
##indentity matrix
arr5 = np.eye(3)
print(arr5,arr5.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [27]:
##range(start,end,step)
arr6 = np.arange(1,11,2)#range elenements
print(arr6,type(arr6),arr6.shape)

[1 3 5 7 9] <class 'numpy.ndarray'> (5,)


In [28]:
arr6 = np.linspace(1,100,4)#evenly spaced arrays
print(arr6,type(arr6),arr6.shape)

[  1.  34.  67. 100.] <class 'numpy.ndarray'> (4,)


In [35]:
#properties
brr = np.array([1,2,3,4,5])
print(brr.shape)
print(brr.size)
print(brr.dtype)
print(brr.ndim)
##type caste
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(5,)
5
int64
1
[1. 2. 3. 4. 5.] float64


In [38]:
##operating on numpoy 
#reshaping 2 *3 => 3*2
arr7 = np.array([[1,2,3],[4,5,6]])
print(arr7,arr7.shape)

reshape = arr7.reshape((3,2))
print(reshape,reshape.shape)

flatteened = arr.flatten() #2D => 1D
print(flatteened,flatteened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [44]:
##indexing 
crr = np.array([[1,2,3],[4,5,6]])
print(crr[0][2])
print(crr[1][2])

#fancy indexing
crr2 = np.array([1,2,3,4,5,6])
idx = [0,1,3]
print(crr2[idx])

3
6
[1 2 4]


In [47]:
#boolean indexing
crr3 = np.array([1,2,3,4,5,6])
print(crr3[crr3>2])
print(crr3[crr3%2==0])
print(crr3[crr3%2!=0])

[3 4 5 6]
[2 4 6]
[1 3 5]


In [52]:
#slicing
brr2 = np.array([1,2,3,4,5])
print(brr2[1:4])
print(brr2[:4])
print(brr2[::])
print(brr2[::2])
print(brr2[1:])

[2 3 4]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]
[2 3 4 5]


In [58]:
#copy as view
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

#no copy in numpy array for slicing 
nums = np.array([1,2,3,4,5])
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(f"orginal numpyarray without copy {nums}")

#if want to create a copy in numoy array 
nums = np.array([1,2,3,4,5])
sub_list = nums[1:3].copy()
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(f"orginal numpyarray with copy {nums}")

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
orginal numpyarray without copy [  1 200   3   4   5]
[2 3]
[200   3]
orginal numpyarray with copy [1 2 3 4 5]
